repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: mixed-line-ending
      - id: trailing-whitespace
        exclude: (doc/ReleaseNotes.md)
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: .github/scripts/clang-format-hook
        types: [c++]
        language: system
  - repo: https://github.com/johann-petrak/licenseheaders.git
    rev: 'v0.8.8'
    hooks:
      - id: licenseheaders
        args: ["-t", ".github/templates/apache-2.tmpl", "-y2014-2023",
        "-o", "Key4hep-Project",
        "-n", "Key4hep",
        "-u", "https://key4hep.github.io/key4hep-doc/",
        "-x", ".github/*", ".pre-commit-config.yaml", "README.md",
              "doc/ReleaseNotes.md", ".k4fwcore-ci.d/*", "init.sh",
        "-f"]
