#[[
Copyright (c) 2014-2024 Key4hep-Project.

This file is part of Key4hep.
See https://key4hep.github.io/key4hep-doc/ for further info.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
]]

# Test helpers for k4FWCore and for projects using it. They are available after
# find_package(k4FWCore). All tests run through the `run` script generated by
# Gaudi, which sets up the build-tree environment (PATH, LD_LIBRARY_PATH,
# PYTHONPATH, GAUDI_PLUGIN_PATH, ROOT_INCLUDE_PATH) of every library, plugin,
# executable, script and python package declared with the gaudi_* functions, so
# no hand-written test environment is needed.

include_guard(GLOBAL)

# Regular expression used to fail a test that prints Gaudi ERROR or FATAL
# messages. It can be changed before declaring the tests.
if(NOT DEFINED K4FWCORE_TEST_ERROR_REGEX)
  set(K4FWCORE_TEST_ERROR_REGEX " (ERROR|FATAL) ")
endif()

#[[
.. command:: k4fwcore_add_test

  .. code-block:: cmake

    k4fwcore_add_test(<name> COMMAND <command> [<arg>...]
                      [WORKING_DIRECTORY <dir> | PRIVATE_WORKING_DIRECTORY]
                      [ENVIRONMENT <var>=<value>...]
                      [LABELS <label>...]
                      [FIXTURES_SETUP <fixture>...]
                      [FIXTURES_REQUIRED <fixture>...]
                      [CHECK_ERROR_MESSAGES]
                      [PROPERTIES <property> <value>...])

  Adds a test that runs ``<command>`` in the environment of the build tree.
  If ``BUILD_TESTING`` is false, this call is a no-op.

  ``COMMAND``
    Command to run. If the first element is the name of an executable target,
    it is replaced by the path to the executable.

  ``WORKING_DIRECTORY``
    Directory where the test runs, by default ``CMAKE_CURRENT_BINARY_DIR``.

  ``PRIVATE_WORKING_DIRECTORY``
    Run the test in its own directory, ``${CMAKE_CURRENT_BINARY_DIR}/<name>.dir``,
    so that its outputs do not clash with those of other tests.

  ``ENVIRONMENT``
    Additional environment variables. They are set before the build
    environment, so path-like variables (``PATH``, ``PYTHONPATH``, ...) are
    searched after the build tree.

  ``LABELS``
    Labels in addition to ``${PROJECT_NAME}``, which is always added.

  ``FIXTURES_SETUP``, ``FIXTURES_REQUIRED``
    CTest fixtures that this test provides or needs, e.g. to make a test that
    reads a file run after the test that produces it.

  ``CHECK_ERROR_MESSAGES``
    Fail the test if the output matches ``K4FWCORE_TEST_ERROR_REGEX``, i.e. if
    a Gaudi ``ERROR`` or ``FATAL`` message is printed. Setting the
    ``FAIL_REGULAR_EXPRESSION`` property afterwards replaces this check.

  ``PROPERTIES``
    Any other CTest properties, forwarded to ``set_tests_properties``.
#]]
function(k4fwcore_add_test name)
  if(NOT BUILD_TESTING)
    return()
  endif()
  cmake_parse_arguments(PARSE_ARGV 1 ARG
    "PRIVATE_WORKING_DIRECTORY;CHECK_ERROR_MESSAGES"
    "WORKING_DIRECTORY"
    "COMMAND;ENVIRONMENT;LABELS;FIXTURES_SETUP;FIXTURES_REQUIRED;PROPERTIES")

  if(ARG_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "k4fwcore_add_test(${name}): unknown arguments ${ARG_UNPARSED_ARGUMENTS}")
  endif()
  if(NOT ARG_COMMAND)
    message(FATAL_ERROR "k4fwcore_add_test(${name}): COMMAND is required")
  endif()
  if(NOT TARGET run)
    message(FATAL_ERROR "k4fwcore_add_test(${name}): the 'run' target from Gaudi is "
                        "not available, find_package(Gaudi) must be called first")
  endif()
  if(ARG_WORKING_DIRECTORY AND ARG_PRIVATE_WORKING_DIRECTORY)
    message(FATAL_ERROR "k4fwcore_add_test(${name}): WORKING_DIRECTORY and "
                        "PRIVATE_WORKING_DIRECTORY are mutually exclusive")
  endif()

  if(ARG_PRIVATE_WORKING_DIRECTORY)
    set(working_directory ${CMAKE_CURRENT_BINARY_DIR}/${name}.dir)
    file(MAKE_DIRECTORY ${working_directory})
  elseif(ARG_WORKING_DIRECTORY)
    set(working_directory ${ARG_WORKING_DIRECTORY})
  else()
    set(working_directory ${CMAKE_CURRENT_BINARY_DIR})
  endif()

  # add_test only resolves target names for the first element of the command,
  # which is `run` here
  list(GET ARG_COMMAND 0 executable)
  if(TARGET ${executable})
    get_target_property(target_type ${executable} TYPE)
    if(target_type STREQUAL "EXECUTABLE")
      list(REMOVE_AT ARG_COMMAND 0)
      list(PREPEND ARG_COMMAND $<TARGET_FILE:${executable}>)
    endif()
  endif()

  add_test(NAME ${name}
           COMMAND $<TARGET_FILE:run> ${ARG_COMMAND}
           WORKING_DIRECTORY ${working_directory})

  set_property(TEST ${name} APPEND PROPERTY LABELS ${PROJECT_NAME} ${ARG_LABELS})
  if(ARG_ENVIRONMENT)
    set_property(TEST ${name} APPEND PROPERTY ENVIRONMENT ${ARG_ENVIRONMENT})
  endif()
  if(ARG_FIXTURES_SETUP)
    set_property(TEST ${name} APPEND PROPERTY FIXTURES_SETUP ${ARG_FIXTURES_SETUP})
  endif()
  if(ARG_FIXTURES_REQUIRED)
    set_property(TEST ${name} APPEND PROPERTY FIXTURES_REQUIRED ${ARG_FIXTURES_REQUIRED})
  endif()
  if(ARG_CHECK_ERROR_MESSAGES)
    set_property(TEST ${name} PROPERTY FAIL_REGULAR_EXPRESSION "${K4FWCORE_TEST_ERROR_REGEX}")
  endif()
  if(ARG_PROPERTIES)
    set_tests_properties(${name} PROPERTIES ${ARG_PROPERTIES})
  endif()
endfunction()

#[[
.. command:: k4fwcore_add_k4run_test

  .. code-block:: cmake

    k4fwcore_add_k4run_test(<name> OPTIONS <options_file> [ARGS <arg>...]
                            [NO_ERROR_CHECK]
                            [<k4fwcore_add_test arguments>...])

  Adds a test that runs ``k4run <options_file> <arg>...``. All the arguments
  of ``k4fwcore_add_test`` except ``COMMAND`` are accepted.

  ``OPTIONS``
    Steering file. A relative path is taken relative to
    ``CMAKE_CURRENT_SOURCE_DIR`` if the file exists there, otherwise it is
    passed as is and resolved relative to the working directory when the test
    runs (e.g. for files produced by another test).

  ``ARGS``
    Arguments for k4run, e.g. ``--num-events 10`` or ``--IOSvc.Output out.root``.

  ``NO_ERROR_CHECK``
    Do not fail the test when ``ERROR`` or ``FATAL`` messages are printed. By
    default they make the test fail, see ``CHECK_ERROR_MESSAGES``.
#]]
function(k4fwcore_add_k4run_test name)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "NO_ERROR_CHECK" "OPTIONS" "ARGS")
  if(NOT ARG_OPTIONS)
    message(FATAL_ERROR "k4fwcore_add_k4run_test(${name}): OPTIONS is required")
  endif()

  set(options_file ${ARG_OPTIONS})
  if(NOT IS_ABSOLUTE ${options_file} AND EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/${options_file})
    set(options_file ${CMAKE_CURRENT_SOURCE_DIR}/${options_file})
  endif()

  set(error_check CHECK_ERROR_MESSAGES)
  if(ARG_NO_ERROR_CHECK)
    set(error_check)
  endif()

  # k4run is found in PATH: from the build tree of k4FWCore when it is part of
  # the same build, otherwise from the environment used to configure
  k4fwcore_add_test(${name}
                    COMMAND k4run ${options_file} ${ARG_ARGS}
                    ${error_check}
                    ${ARG_UNPARSED_ARGUMENTS})
endfunction()
